server.port=8080
spring.application.name=EvenTech
spring.data.mongodb.uri=mongodb+srv://rafaelfferreira224_db_user:LMZolNXqRx28rBai@cluster0.123suqn.mongodb.net/?appName=Cluster0
spring.neo4j.uri=neo4j+s://22943ed5.databases.neo4j.io
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=mWKG-KQtSf3fp7b5SvLKHZQ-MhBdF9NuohTwMD2BxUA